CREATE TABLE IF NOT EXISTS sp_material_demand_plan (
  id varchar(64) NOT NULL,
  order_code varchar(64) DEFAULT NULL,
  product_serial_no varchar(64) DEFAULT NULL,
  task_serial_no varchar(64) DEFAULT NULL,
  product_name varchar(200) DEFAULT NULL,
  work_center_name varchar(200) DEFAULT NULL,
  work_center_code varchar(64) DEFAULT NULL,
  materiel_code varchar(64) DEFAULT NULL,
  materiel_name varchar(200) DEFAULT NULL,
  require_qty decimal(10,2) DEFAULT 1,
  unit varchar(50) DEFAULT NULL,
  demand_date datetime DEFAULT NULL,
  delivery_status varchar(20) DEFAULT 'undelivered',
  stock_out_qty decimal(10,2) DEFAULT 0,
  net_require_qty decimal(10,2) DEFAULT 0,
  stock_in_status varchar(20) DEFAULT 'not_generated',
  stock_in_order_no varchar(64) DEFAULT NULL,
  remark varchar(500) DEFAULT NULL,
  create_time datetime DEFAULT CURRENT_TIMESTAMP,
  create_username varchar(64) DEFAULT NULL,
  update_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  update_username varchar(64) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_order_code (order_code),
  KEY idx_product_serial (product_serial_no),
  KEY idx_materiel_code (materiel_code),
  KEY idx_work_center (work_center_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
